### ISSUE TITLE
unable to configure

### ISSUE THREAD

**Issue by rupadhyay87** [goatherd/php-snappy#3]
hecking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking PHP version... 5.5.24, ok
checking for snappy support... yes, shared
checking for snappy header... yes, shared
checking for snappy files in default path... not found
configure: error: Can't find snappy headers

**Comment by marcelosousaalmeida** [comment]
Make sure you have installed "libsnappy-dev" before running ./configure

**Comment by goatherd** [comment]
Official repo is found at https://github.com/kjdev/php-ext-snappy
